### ISSUE TITLE
Incorrect example format for emails field in /users.list schema

### ISSUE THREAD

**Issue by makanddream** [outline/openapi#9]
# Describe the bug

The OpenAPI schema for the `/users.list` endpoint currently has an incorrect example format under the `emails` array field. The example is set on the `items` level as an array, which results in validation errors when the example is used.

## Current (Incorrect):

```yaml
emails:
  type: array
  items:
    type: string
    description: Array of emails
    example: ["jane.crandall@mail.com", "prudence.crandall@mail.com"]
```

## Resulting error:

```json
{
  "ok": false,
  "error": "validation_error",
  "status": 400,
  "message": "0: Expected string, received array"
}
```

# Expected behavior

The `example` for an array should be defined at the array level, not at the `items` level. When moved, the request validates and functions as expected.

## Corrected version:

```yaml
emails:
  type: array
  description: Array of emails
  items:
    type: string
  example:
    - "jane.crandall@mail.com"
    - "prudence.crandall@mail.com"
```

# Additional context

Moving the `example` to the array level aligns with OpenAPI spec expectations and avoids the `Expected string, received array` validation error.

Let me know if you'd like a PR with the fix!
